name: Service
properties:
    name:
        type: STRING
        default: "\"UNKNOWN\""
relations:
    needs:
        type: needs
        other_classnames:
            - Capability
uri:
    # This should build "http://rock-robotics.org/2014/01/om-schema/<name>"
    scheme: "http"
    root_path: "//rock-robotics.org/2014/01/om-schema"
    from:
        - name: name
